### ISSUE TITLE
Deepadungpalaung version of 1_select.py 

### ISSUE THREAD

**Issue by Juunlee** [lexibank/deepadungpalaung#9]
Here is the code that I modified for the Deepadungpalaung version of 1_select.py.

"""
Create a subselection of doculects and concepts from the dataset of Deepadung et al 2015.
"""
from lexibank_deepadungpalaung import Dataset
from lingpy import *
from pyconcepticon import Concepticon
from cldfcatalog import Config
from tabulate import tabulate

from sys import argv

ds = Dataset()
concepticon = Concepticon(Config.from_file().get_clone('concepticon'))
wl = Wordlist.from_cldf(
        ds.dir.joinpath('cldf', 'cldf-metadata.json'),
        )

# languages
languages = [
        "ChuDongGua",
        "MengDan",
        "NanSang",
        "GuangKa",
        "MangBang",
        "ChaYeQing",
        "XiangZhaiTang",
        "NamHsan",
        "KhunHawt",
        "HtanHsan",
        "PangKham",
        "ManLoi",
        "NyaungGone",
        "BanPaw",
        "NoeLae",
        "PongNuea"]  

# concepts
concepts = set()
for clist in [
        'Blust-2008-210', 
        'Swadesh-1952-200', 
        'Swadesh-1955-100',
        'Comrie-1977-207', 
        'Matisoff-1978-200',
        'Sagart-2019-250',
        'Liu-2007-201',
        'SoHartmann-1988-280',
        'BeijingDaxue-1964-905',
        'Deepadung-2015-100']:
    for concept in concepticon.conceptlists[clist].concepts.values():
            if concept.concepticon_id:
                concepts.add(concept.concepticon_id)

if not 'all' in argv:
    D = {0: wl.columns}
    for idx, doculect, cid in wl.iter_rows('doculect', 'concepticon'):
        if doculect in languages and cid in concepts:
            D[idx] = wl[idx]
    
    Wordlist(D).output('tsv', filename='D_Deepadung_subset', prettify=False)
    # revise columns commend
    wl = Wordlist('D_Deepadung_subset.tsv')

else:
    wl.output('tsv', filename='A_Deepadung_subset', prettify=False)

print('Wordlist has {0} concepts and {1} varieties across {2} words.'.format(
      wl.height, wl.width, len(wl)))

# print statistics on coverage
table = [[doculect, items, items/wl.height] for doculect, items in wl.coverage().items()]
print(tabulate(table, headers=['Doculect', 'Words', 'Coverage'],
    tablefmt='pipe', floatfmt='.2f'))

I added 'Deepadung-2015-100' to the clist. As a result, we only got to compare 1 concept for 16 languages. Below is the exact output we got when we ran the code. I am not exactly sure how to solve this 1 concept problem.   

Wordlist has 1 concept and 16 varieties across 1585 words.
| Doculect      |   Words |   Coverage |
|:--------------|--------:|-----------:|
| BanPaw        |       1 |       1.00 |
| ChaYeQing     |       1 |       1.00 |
| ChuDongGua    |       1 |       1.00 |
| GuangKa       |       1 |       1.00 |
| HtanHsan      |       1 |       1.00 |
| KhunHawt      |       1 |       1.00 |
| MangBang      |       1 |       1.00 |
| ManLoi        |       1 |       1.00 |
| MengDan       |       1 |       1.00 |
| NamHsan       |       1 |       1.00 |
| NanSang       |       1 |       1.00 |
| NoeLae        |       1 |       1.00 |
| NyaungGone    |       1 |       1.00 |
| PangKham      |       1 |       1.00 |
| PongNuea      |       1 |       1.00 |
| XiangZhaiTang |       1 |       1.00 |

**Comment by LinguList** [comment]
I think I fixed the one-concept problem yesterday. You should pull the data. This is also what crashed your computer.

**Comment by LinguList** [comment]
The reason is you used "gloss" instead of "english":

https://github.com/lexibank/deepadungpalaung/blob/e1c7c423689615480c0d9c7d5e84027af2979281/lexibank_deepadungpalaung.py#L45-L50

I already changed that, if you pull and run the code now, this problem should have disappeared.

**Comment by danbriggs** [comment]
Hi Junsung,

I don't know how I followed the same instructions twice at two different times and they only worked the second time, but here is what worked for me.

First, make sure lines 45–50 of your lexibank_deepadungpalaung.py match the above.

Next, when in your deepadungpalaung folder in Terminal, type the following:

    pip install -e git+https://github.com/lexibank/deepadungpalaung.git#egg=lexibank_deepadungpalaung

I got the above by reading requirements.txt from workflow-paper, you should take a look at that .txt file too.
You might have to say "pip3" instead of pip, depending on your Python/pip version matching.

Next run the following:

    cldfbench lexibank.makecldf deepadungpalaung

I got the above from the EDICTOR tutorial. I believe that it is what calls cmd_makecldf() appropriately.

Finally,

    py 1_select.py

remember that your Python call might be spelled differently, as "python3" or "python". Make sure to type "py --version" etc. to find out what version of Python each runs. You want to make sure it's not Python 2 but rather Python 3.

If you run into a UnicodeEncodeError running the above line, do

    export PYTHONIOENCODING=utf-8

and then rerun it. But I think it's just my Windows 7 machine that needs to be told to use Unicode :-)
